// settings.js
// credit by Kevin tech 

const config = require('./setting/config');


const settings = {
  SESSION_ID: config.SESSION_ID || "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0hHNkluUlFVNHlzOERCdlI0M0VKNGdheW56cGpDbW83SERtSnRJVFgzRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic015QUFsM2RkQ0V4ZjFxUFIzaXJBa2RjK0hmS3pzQXpqUTJTK2diODdEOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwT2FFRFlVaml5SGVnK2JzY0ppMElvQmlNZnBwVHJMeGVNZXBydXN2alVVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrM2Joa2R0NXhLTjhqOUhXckFxbjR0cW5ZZE1wVkJ3M2JuOGIwRHcxT1JzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndNVUhOY1ZWOXFzNmZ6S1htRUFaMkM0RkY1S2xNM0NuaC9vSHo4REc2bFU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVxcCt5ZXd3V1BPMk5jdkZvVjRJTXUzZnFDTlNKZC9ydDlhWDJkcmlHeEE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0VkbTJtOFJ1MmRzcHZzd1d4VExGZ0k2cW5YYkdyNlordWh1VEZJRWRYRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRk4yWmlQalcwS1F4MDlkdkpnaThrV0RrSmtKdW5ISW1Cb2dhaFR1REloMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlhqTy94L1J0SDc5WGxSVlZHeHpueVhvY0VWaklUUG5sb0EvNmZRSHQ4TlVsY3haTUpHRzA4Zjd0dnJUVlF3KzRkUWtFVmFJWFQwVGlSNE82ZnJEYUFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTU2LCJhZHZTZWNyZXRLZXkiOiJGTzBtUHFhU3hPY2RFYkpXcE1BclM3dXgwVElwNGNPVHByTmFrTHpxRTBjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI3Njg3NjUxMTM2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDQjExQjAwRjEzQkMzOENGMTFGQzg2ODMyNEY2MDA3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTkwMTM5MzR9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI3Njg3NjUxMTM2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDNDdGQjA2QUU3Njc4Q0Y0N0FGMzc1RUVBMTM2QjJGIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTkwMTM5MzZ9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjNHM1YxWFpIIiwibWUiOnsiaWQiOiIyNzY4NzY1MTEzNjoyQHMud2hhdHNhcHAubmV0IiwibGlkIjoiMjY5NjM4MzE1MjgyNjU2OjJAbGlkIiwibmFtZSI6Ik0yMyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTlR4bGJNQkVKM1k0Y1lHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiSDNRYXpIUmwwRDdiL2xLUFV2OG5KampacGVVYU9SN3Ira1d2Z0wvSWRIRT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiYUtidHpVMitaQVVVVi9NLytZZDRJMCs0SERSdFNMVERFMDJLUkVsMzhQVnQ5SWpNeHVWQ0VPT0xucFBQUGZsazBOMkhDTFlxRmNBZ1BGU3lIOFhOQ1E9PSIsImRldmljZVNpZ25hdHVyZSI6IlZ0eWx2djBxN3JjYlZOckFDVUx2ellhcmhNZU92dWJqWnNWVlV5Ly9LVWFDYTRsRGFPMlZpSTd3eEM4Qm80NGM4NWpjanBKTnRiZGZKdkxibVpobkJBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjc2ODc2NTExMzY6MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJSOTBHc3gwWmRBKzIvNVNqMUwvSnlZNDJhWGxHamtlNi9wRnI0Qy95SFJ4In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWdJQWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTkwMTM5MzIsImxhc3RQcm9wSGFzaCI6IjFLNGhINCIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSjBhIn0=", // enter session id
  ownername: config.ownername || "ᴋᴇʟᴠɪɴ ᴛᴇᴄʜ", // Owner name
  botname: config.botname || "ᴠɪɴɪᴄ xᴍᴅ", // custom bot name
  prefa: config.prefa || ['.', '!'], // Command prefixes
  owner: config.owner || ["256742932677"] // Owner phone numbers
};

// Export settings for use in other modules
module.exports = settings;

// Watch for changes to this file and reload if updated
const fs = require('fs');
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log('\x1b[0;32m' + __filename + ' \x1b[1;32mupdated!\x1b[0m');
  delete require.cache[file];
  require(file);
});
