// settings.js
// credit by Kevin tech 

const config = require('./setting/config');


const settings = {
  SESSION_ID: config.SESSION_ID || "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR082MWpjenFoNUp0UlJnVFVDNEZBZ01aVzB4N3RIQmE3ZTZRdm05dVJtdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiakpJL1JGeEJVTGFPWWxDVGNGd0VsaGdTaUc3UDhWUWZyTy8rRG9CV0dnZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjRE1pNitHYlNBdWlPakJQUVI0ZjVXWkhNZXkxaWE4ZWRzN0g1V2phV0ZVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJV2FxZVFqdHVncW80dGd5T0MzcDB6ekgxVTl4eE9OWkdMQlZhbDF6em1JPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVDQkZRait3Z1pmYmdmayt6Y21tYXRIVkpSTjE0Q05hZ3hrbWF5RGdZRWM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjdsZFFiNzI0Y2VDWjJxeUJEeUhzNTlBMzlRNmt5TUNJZUQvdUp4cGtwaG89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidU1RTHh2TkNUU2dJcEJkRktJK1VkK1E5N1lWTUEyWEVDTVBiZDJZeklYcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieXk4N2p0Z2I5bis2TEYxN2FPVGJCaTcvMTFlWFdDaVBPUnNqQ3ErOHpCOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjE1ZjUyUklBUVIwTFJEZDMzcSt6bWI1RUc0a0t5SVZ4TDZScUN2Qy9UWERaUzUrSy9LQWlDUForaXBqZU1KTTlpdnB3R05QenlkUzJZMEtVcnVqVWh3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjMyLCJhZHZTZWNyZXRLZXkiOiJmd1NjcElSRk04aTNaNHRYUVRSTXBIempYeUlkVGV5elpFQlMwVXBic25RPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJZR0JNUlhQUCIsIm1lIjp7ImlkIjoiMjc2ODc2NTExMzY6OTNAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIyNjk2MzgzMTUyODI2NTY6OTNAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNJaUFoaU1RcGE3UnhnWVlCU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJXc1h2NDQraWxtS3U0R3dnRlROSFN5d01GSnhuenE3aDZNb3BIQ0ZQcm1vPSIsImFjY291bnRTaWduYXR1cmUiOiJMVnEwd3MvRys4alVqdHNLdXBiKzVBRGZsWDFMYnh4OUlXNGZFOUdCY3hldUtKbVVVdytsZWtFQ1lCOFZXVXZ5N09TMHE4REZObVJBSnQ4WmVvNG1BQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiVmJWbWtyT0NCNGRXSVpWUmtnd0xYS1Y4TVd2TklXdmphUGhwRVV0V0Rob3IyWGUxZGg4dysrekVrSDdlSFlGZUlNNVRaS05Yc1NYZnIzaVZmWUpHaEE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNzY4NzY1MTEzNjo5M0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWckY3K09Qb3BaaXJ1QnNJQlV6UjBzc0RCU2NaODZ1NGVqS0tSd2hUNjVxIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWdJQWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTg3NDY0MjAsImxhc3RQcm9wSGFzaCI6IjFLNGhINCIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSFN3In0=", // enter session id
  ownername: config.ownername || "ᴋᴇʟᴠɪɴ ᴛᴇᴄʜ", // Owner name
  botname: config.botname || "ᴠɪɴɪᴄ xᴍᴅ", // custom bot name
  prefa: config.prefa || ['.', '!'], // Command prefixes
  owner: config.owner || ["256742932677"] // Owner phone numbers
};

// Export settings for use in other modules
module.exports = settings;

// Watch for changes to this file and reload if updated
const fs = require('fs');
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log('\x1b[0;32m' + __filename + ' \x1b[1;32mupdated!\x1b[0m');
  delete require.cache[file];
  require(file);
});
